name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Rupesh#@121
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: Rupesh#@121
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # Step 1: Set up PHP environment
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, bcmath, pdo_mysql

    # Step 2: Check out code
    - uses: actions/checkout@v4

    # Step 3: Copy .env
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # Step 5: Generate app key
    - name: Generate key
      run: php artisan key:generate

    # Step 6: Set directory permissions
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Step 7: Configure MySQL Database
    - name: Configure .env for MySQL
      run: |
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=test_db/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=test_user/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=Rupesh#@121/' .env

    # Step 8: Run migrations and seeders
    - name: Run Migrations
      run: php artisan migrate --force

    # Step 9: Run Tests
    - name: Run Tests
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: test_db
        DB_USERNAME: test_user
        DB_PASSWORD: Rupesh#@121
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
    # Step 1: Check out code
    - uses: actions/checkout@v4

    # Step 2: Upload to FTP server
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: doctor.aaditya.edu.np
        username: doctor@doctor.aaditya.edu.np
        password: Rupesh#@121
        local-dir: ./
        server-dir: /home/aadityae/doctor.aaditya.edu.np
